{
 "title": "A SYSTEM STATUS",
 "tags": [
  "product",
  "system",
  "cluster"
 ],
 "time": { "from": "now-4h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "ingress-nginx" },
   {
    "name": "controller_class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class) "
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
    }
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, ingress)"
    }
   },
   { "name": "node", "query": ".*" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kube_node_info{node=~\"$node\"}, internal_ip)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(nginx_ingress_controller_request_duration_seconds_bucket{controller_namespace=\"ingress-nginx\",controller_class=~\"$controller_class\"}, status)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Microservices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services status",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"services\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Subscribers status",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"subscriber\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Releases date",
   "type": "table",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_deployment_created{namespace=\"services\"} * 1000",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_deployment_created{namespace=\"subscriber\"} * 1000",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_deployment_created{namespace=\"frontend\"} * 1000",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Kube-system services status",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"kube-system\"}",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_statefulset_status_replicas{namespace=\"kube-system\"}",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Frontend status",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"frontend\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Infra services status",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"infra\"}",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_statefulset_status_replicas{namespace=\"infra\"}",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "400x, 500x error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum (increase(nginx_ingress_controller_request_duration_seconds_count{exported_service!=\"\",status=~\"[4-5].*\"}[5m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Current RPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Frontend success rate and latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/\",ingress=\"driveaway-ui\",exported_service=\"driveaway-ui\",controller_class=\"nginx\",status=\"200\"}[60m])) by (le))",
     "legendFormat": "200 OK"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/\",ingress=\"driveaway-ui\",exported_service=\"driveaway-ui\",controller_class=\"nginx\",status!=\"200\"}[60m])) by (le))",
     "legendFormat": "non 200 not OK"
    }
   ]
  },
  {
   "title": "Backend success rate and latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"driveaway-ui\",exported_service!=\"driveaway-ui\",controller_class=\"nginx\",status=\"200\"}[60m])) by (le))",
     "legendFormat": "200 OK"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"driveaway-ui\",exported_service!=\"driveaway-ui\",controller_class=\"nginx\",status!=\"200\"}[60m])) by (le))",
     "legendFormat": "non 200 not OK"
    }
   ]
  },
  {
   "title": "Certificate expiration status",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 19 },
   "targets": [
    {
     "expr": "(avg(nginx_ingress_controller_ssl_expire_time_seconds{app_kubernetes_io_name=\"ingress-nginx\", class=\"nginx\", container=\"controller\", endpoint=\"metrics\", exported_namespace=\"ingress-nginx\", host=~\".[a-z].drivrzxchange.com\",}) by (host)) * 1000",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Total errors from last 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(nginx_ingress_controller_requests{namespace=\"$namespace\",exported_service!=\"\",status=~\"[4-5].*\"}[24h]))"
    }
   ]
  },
  {
   "title": "Ingress replicas status",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 23 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"ingress-nginx\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Servers OFFLINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "LOW DISK servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "LOW MEMORY servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "OOM pods 30m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"}[30m]))"
    }
   ]
  },
  {
   "title": "Kubertenes API Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"read\", cluster=\"$cluster\", code!=\"200\"}>5))",
     "legendFormat": "read errors"
    },
    {
     "expr": "count(sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"write\", cluster=\"$cluster\", code!=\"200\"})>5)",
     "legendFormat": "write erros"
    }
   ]
  },
  {
   "title": "Servers online",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Avg mem usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Avg CPU load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Avg servers load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_load5{})) /  sum(count(count(node_cpu_seconds_total{}))) by (cpu) / sum(kube_node_info{}) * 100"
    }
   ]
  },
  {
   "title": "Srvs 85% CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(((\n  instance:node_cpu_utilisation:rate5m{job=\"node-exporter\"}\n  *\n  instance:node_num_cpu:sum{job=\"node-exporter\"}\n) != 0 )\n/ scalar(sum(instance:node_num_cpu:sum{job=\"node-exporter\"})) > 0.85)"
    }
   ]
  },
  {
   "title": "Restarted pods 6h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{}[6h]))"
    }
   ]
  },
  {
   "title": "HIGH PID servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "CPU Saturation > 100%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count ((\n  instance:node_load1_per_cpu:ratio{job=\"node-exporter\", cluster=\"$cluster\"}\n  / scalar(count(instance:node_load1_per_cpu:ratio{job=\"node-exporter\", cluster=\"$cluster\"}))\n) > 1)"
    }
   ]
  },
  {
   "title": "Srvs 85% Memory load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count ((\n  instance:node_memory_utilisation:ratio{job=\"node-exporter\", cluster=\"$cluster\"}\n  / scalar(count(instance:node_memory_utilisation:ratio{job=\"node-exporter\", cluster=\"$cluster\"}))\n) > 0.85)"
    }
   ]
  },
  { "title": "AWS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Elasticsearch cluster status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_es_cluster_status_green_minimum{}",
     "legendFormat": "GREEN"
    },
    {
     "expr": "aws_es_cluster_status_yellow_maximum{}",
     "legendFormat": "YELLOW"
    },
    {
     "expr": "aws_es_cluster_status_red_maximum{}",
     "legendFormat": "RED"
    }
   ]
  },
  {
   "title": "DLQ amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aws_sqs_approximate_number_of_messages_visible_average{dimension_QueueName=~\".*DLQ.fifo\"}>0)",
     "legendFormat": "now"
    },
    {
     "expr": "count(last_over_time(aws_sqs_approximate_number_of_messages_visible_average{dimension_QueueName=~\".*DLQ.fifo\"}[24h])>0)",
     "legendFormat": "last 24h"
    }
   ]
  },
  {
   "title": "SNS Fails",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(aws_sns_number_of_notifications_failed_sum{}[24h])>0)"
    }
   ]
  },
  {
   "title": "ES Mem Press",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_es_jvmmemory_pressure_average{dimension_NodeId=\"\"}"
    }
   ]
  },
  {
   "title": "ES Free space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_es_free_storage_space_average{dimension_NodeId=\"\"} / 1024"
    }
   ]
  },
  {
   "title": "ES CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_es_cpuutilization_average{dimension_NodeId=\"\"}"
    }
   ]
  },
  {
   "title": "RDS CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dimension_DBInstanceIdentifier!=\"\"}"
    }
   ]
  },
  {
   "title": "RDS Free Storage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{dimension_DatabaseClass!=\"\"} / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "RDS Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{dimension_DBInstanceIdentifier!=\"\"}"
    }
   ]
  },
  {
   "title": "RDS Mem Free",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{dimension_DatabaseClass!=\"\"} / 1024 / 1024 / 1024"
    }
   ]
  },
  { "title": "Alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Services state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"services\"}",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_deployment_status_replicas{namespace=\"subscriber\"}",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_deployment_status_replicas{namespace=\"frontend\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Servers problems",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 39 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"})"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\"})"
    },
    {}
   ]
  },
  {
   "title": "Servers State",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 39 },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{})"
    },
    { "expr": "sum(kube_node_info{})" }
   ]
  },
  {
   "title": "DB CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "aws_es_cpuutilization_average{dimension_DomainName=\"driveaway-sbx\",dimension_NodeId=\"\"}",
     "legendFormat": "es"
    },
    {
     "expr": "aws_rds_cpuutilization_average{dimension_DBInstanceIdentifier!=\"\"}",
     "legendFormat": "rds"
    }
   ]
  },
  {
   "title": "DB Storage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 39 },
   "targets": [
    {
     "expr": "aws_es_free_storage_space_average{dimension_NodeId=\"\"} / 1024",
     "legendFormat": "es"
    },
    {
     "expr": "aws_rds_free_storage_space_average{dimension_DatabaseClass!=\"\"} / 1024 / 1024 / 1024",
     "legendFormat": "rds"
    }
   ]
  },
  {
   "title": "DB connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{dimension_DBInstanceIdentifier!=\"\"}"
    }
   ]
  },
  {
   "title": "ES Cluster status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 39 },
   "targets": [
    {
     "expr": "aws_es_cluster_status_yellow_maximum{}"
    },
    {
     "expr": "aws_es_cluster_status_red_maximum{}"
    }
   ]
  }
 ]
}