{
 "title": "App Logs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dxc_app", "label": "application", "query": "label_values(dxc_app)" },
   { "name": "search" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{dxc_app=\"$dxc_app\"} | json |~ \"$search\""
    }
   ]
  },
  {
   "title": "Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events Rate / type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({dxc_app=\"$dxc_app\"} | json [10m])) by (level)",
       "legendFormat": "{{ level }}"
      }
     ]
    },
    {
     "title": "Total WARNINGS / 24h",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"services\"}| json | level =~ \"warning\" [24h])) by (dxc_app)"
      }
     ]
    },
    {
     "title": "Total ERRORS / 24h",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 19, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"services\"}| json | level =~ \"error\" [24h])) by (dxc_app)"
      }
     ]
    }
   ]
  }
 ]
}