{
 "title": "A Ingress analytics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "label_name", "label": "Label Name", "query": "app_kubernetes_io_name" },
   { "name": "label_value", "label": "Label Value", "query": "ingress-nginx" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({$label_name=~\"$label_value\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({$label_name=~\"$label_value\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (httpRequest_status) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{httpRequest_status}}"
    }
   ]
  },
  {
   "title": "Realtime visitors ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (log_httpRequest_remoteIp) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json |  __error__=\"\" [5m])))"
    }
   ]
  },
  {
   "title": "visitors/selected time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (log_httpRequest_remoteIp) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "Top 10 Requested Pages",
   "type": "table",
   "gridPos": { "h": 20, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (httpRequest_requestUrl) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | __error__=\"\" [15m])))",
     "legendFormat": "{{ httpRequest_requestUrl }}"
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "table",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sum by (geoip_country_code) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | geoip_country_code != \"\" and  __error__=\"\" [$__interval])))",
     "legendFormat": "{{httpRequest_remoteIp}}"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | line_format \"➡️ {{.httpRequest_request_method}} {{.httpRequest_request_uri}} with HTTP status: {{.httpRequest_status}} \""
    }
   ]
  },
  {
   "title": "Requests per Country",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | geoip_country_code != \"\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Top 10 visitor IPs",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (httpRequest_remoteIp, geoip_country_code) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json |  __error__=\"\" [15m])))",
     "legendFormat": "{{httpRequest_remoteIp}}"
    }
   ]
  },
  {
   "title": "Top 10 User Agents",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "topk(10, sum by (httpRequest_userAgent) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json |  __error__=\"\" [15m])))",
     "legendFormat": "{{httpRequest_userAgent}}"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |= \"Googlebot\")[$__interval])) / (sum(count_over_time(({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} != \"Googlebot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | httpRequest_status >= 500 |__error__=\"\"[$__interval])) / (sum(count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | __error__=\"\"[$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (httpRequest_status) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{httpRequest_status}}"
    }
   ]
  },
  {
   "title": "Top 10 HTTP Referers",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 27 },
   "targets": [
    {
     "expr": "topk(10, sum by (httpRequest_http_referer) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json |  httpRequest_http_referer != \"\" and httpRequest_http_referer !~ \".*?$host.*?\" and httpRequest_http_referer !~ \".*?\\\\*\\\\*\\\\*.*?\" | __error__=\"\" [15m])))",
     "legendFormat": "{{httpRequest_http_referer}}"
    }
   ]
  },
  {
   "title": "Backend Requests by time (s)",
   "type": "timeseries",
   "gridPos": { "h": 26, "w": 21, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | proxyUpstreamName =~ \".+-api-.+\" | unwrap request_time |  __error__=\"\"  [$__interval]) by (httpRequest_requestUrl)",
     "legendFormat": "{{ httpRequest_requestUrl }}"
    }
   ]
  },
  {
   "title": "Frontend Requests by time (s)",
   "type": "timeseries",
   "gridPos": { "h": 26, "w": 21, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | proxyUpstreamName !~ \".+-api-.+\" | unwrap request_time |  __error__=\"\"  [$__interval]) by (httpRequest_requestUrl)",
     "legendFormat": "{{ httpRequest_requestUrl }}"
    }
   ]
  }
 ]
}